name: setup
description: Shared setup for Node.js with pnpm

inputs:
  node-version-file:
    description: Path to .nvmrc file
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: ${{ inputs.node-version-file }}

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies using pnpm
      run: pnpm install