import type { Metadata } from "next";
import {NextIntlClientProvider} from 'next-intl'
import {unstable_setRequestLocale} from 'next-intl/server'
import {getMessages} from '@/i18n'
import {MagiProduct} from "@/lib/analytics/events";
import {AnalyticsProvider} from "@magi/components/analytics/AnalyticsProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ChatLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = 'en'
  unstable_setRequestLocale(locale)
  const messages = await getMessages(locale)

  // Add fetch user data logic here
  const user = {
    id: '123',
    email: 'test@tripadvisor.com'
  }

  return (
    <AnalyticsProvider product={MagiProduct.chat} userId={user.id} email={user.email}>
      <NextIntlClientProvider locale={locale} messages={messages} timeZone={'UTC'}>
        <div>{children}</div>
      </NextIntlClientProvider>
    </AnalyticsProvider>
  );
}